- hosts: master
  become: yes
  tasks:
    - name: Initialize the Cluster
      shell: kubeadm init --pod-network-cidr=10.2.0.0/16 > cluster_initialized.txt

    - name: Create .kube Directory
      become: yes
      become_user: bennettnw2
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/bennettnw2/.kube/config
        remote_src: yes
        owner: bennettnw2
        group: bennettnw2

    - name: Install Pod Network
      become_user: bennettnw2
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml > pod_network_setup.txt
